// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using herodesknew.Infrastructure.Data.Contexts;

#nullable disable

namespace herodesknew.Infrastructure.Migrations
{
    [DbContext(typeof(HerodesknewDbContext))]
    [Migration("20230721221911_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("herodesknew.Domain.Entities.PullRequest", b =>
                {
                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.Property<int>("TicketId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Url");

                    b.ToTable("PullRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
